#!/usr/bin/env sh
export ZOOKEEPER_VERSION=3.4.12
export SCALA_VERSION=2.12
export KAFKA_VERSION=1.1.0

echo "=-=-=-=-=-=-=- DEBUG INFO =-=-=-=-=-=-=-"
echo "SOURCE_BRANCH: ${SOURCE_BRANCH}"
echo "SOURCE_COMMIT: ${SOURCE_COMMIT}"
echo "COMMIT_MSG: ${COMMIT_MSG}"
echo "DOCKER_REPO: ${DOCKER_REPO}"
echo "DOCKER_TAG: ${DOCKER_TAG}"
echo "IMAGE_NAME: ${IMAGE_NAME}"
echo "ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION}"
echo "SCALA_VERSION: ${SCALA_VERSION}"
echo "KAFKA_VERSION: ${KAFKA_VERSION}"
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"

docker build --build-arg ZOOKEEPER_VERSION=${ZOOKEEPER_VERSION} \
             --build-arg SCALA_VERSION=${SCALA_VERSION} \
             --build-arg KAFKA_VERSION=${KAFKA_VERSION} \
             --no-cache \
             -t $IMAGE_NAME .